version: '3'
services:
  flask: 
    build:
      context: ./flask
    ports:
      - 5001:5000
    volumes:
      - .volumes/staging/flask:/app
    networks:
      - stagingnetwork
  laravel:
    build:
      context: ./laravel
    ports:
      - 8001:8000
    volumes:
      - .volumes/staging/laravel:var/www/html
    networks:
      - stagingnetwork
  react:
    build:
      context: ./react
    ports:
      - 3001:80
    volumes:
      - .volumes/staging/react:/app
    networks:
      - stagingnetwork
networks:
  stagingnetwork: