version: '3'
services:
  flask: 
    build:
      context: ./flask
    ports:
      - 5002:5000
    volumes:
      - .volumes/prod/flask:/app
    networks:
      - prodnetwork
  laravel:
    build:
      context: ./laravel
    ports:
      - 8002:8000
    volumes:
      - .volumes/prod/laravel:var/www/html
    networks:
      - prodnetwork
  react:
    build:
      context: ./react
    ports:
      - 3002:80
    volumes:
      - .volumes/prod/react:/app
    networks:
      - prodnetwork
networks:
  prodnetwork: